FROM node:10.15-stretch-slim

# these package are needed to compile "node-sass" library and generally using webpack
RUN apt-get update && apt-get -y install \
    libglib2.0-0 \
    libnss3 \
    libgtk-3-0 \
    libxss1 \
    libasound2 && \
    rm -rf /var/lib/apt/lists/*
